//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HatsuneMiclock.rc
//
#define IDB_MIKUBMP                     101
#define IDR_HOUR00                      102
#define IDD_ABOUT_DIALOG                102
#define IDR_HOUR01                      103
#define IDR_HOUR02                      104
#define IDR_HOUR03                      105
#define IDR_HOUR04                      106
#define IDD_SETTING_DIALOG              106
#define IDR_HOUR05                      107
#define IDD_NICO_IDPASS                 107
#define IDR_HOUR06                      108
#define IDR_HOUR07                      109
#define IDD_SEARCH_DIALOG               109
#define IDR_HOUR08                      110
#define IDR_HOUR09                      111
#define IDR_HOUR10                      112
#define IDR_HOUR11                      113
#define IDR_HOUR12                      114
#define IDR_HOUR13                      115
#define IDR_HOUR14                      116
#define IDR_HOUR15                      117
#define IDR_HOUR16                      118
#define IDR_HOUR17                      119
#define IDR_HOUR18                      120
#define IDR_HOUR19                      121
#define IDR_HOUR20                      122
#define IDR_HOUR21                      123
#define IDR_HOUR22                      124
#define IDR_HOUR23                      125
#define IDR_MIN01                       126
#define IDR_MIN02                       127
#define IDR_MIN03                       128
#define IDR_MIN04                       129
#define IDR_MIN05                       130
#define IDR_MIN06                       131
#define IDR_MIN07                       132
#define IDR_MIN08                       133
#define IDR_MIN09                       134
#define IDR_MIN10                       135
#define IDR_MIN11                       136
#define IDR_MIN12                       137
#define IDR_MIN13                       138
#define IDR_MIN14                       139
#define IDR_MIN15                       140
#define IDR_MIN16                       141
#define IDR_MIN17                       142
#define IDR_MIN18                       143
#define IDR_MIN19                       144
#define IDR_MIN20                       145
#define IDR_MIN21                       146
#define IDR_MIN22                       147
#define IDR_MIN23                       148
#define IDR_MIN25                       149
#define IDR_MIN27                       150
#define IDR_MIN29                       151
#define IDR_MIN31                       152
#define IDR_MIN33                       153
#define IDR_MIN35                       154
#define IDR_MIN37                       155
#define IDR_MIN39                       156
#define IDR_MIN41                       157
#define IDR_MIN43                       158
#define IDR_MIN45                       159
#define IDR_MIN47                       160
#define IDR_MIN49                       161
#define IDR_MIN51                       162
#define IDR_MIN53                       163
#define IDR_MIN55                       164
#define IDR_MIN57                       165
#define IDR_MIN59                       166
#define IDR_MIN00                       167
#define IDR_MIN24                       168
#define IDR_MIN26                       169
#define IDR_MIN28                       170
#define IDR_MIN30                       171
#define IDR_MIN32                       172
#define IDR_MIN34                       173
#define IDR_MIN36                       174
#define IDR_MIN38                       175
#define IDR_MIN40                       176
#define IDR_MIN42                       177
#define IDR_MIN44                       178
#define IDR_MIN46                       179
#define IDR_MIN48                       180
#define IDR_MIN50                       181
#define IDR_MIN52                       182
#define IDR_MIN54                       183
#define IDR_MIN56                       184
#define IDR_MIN58                       185
#define IDS_FONT                        189
#define IDS_FONTSIZE                    190
#define IDB_BOARD                       190
#define IDS_TEXT_XPOSITION              191
#define IDS_TEXT_YPOSITION              192
#define IDR_CONTEXTMENU                 192
#define IDS_BOARD_XPOSITION             193
#define IDS_BOARD_YPOSITION             194
#define IDI_TASKTRAYICON                194
#define IDS_ERR_ALREADY_CONNECTED       195
#define IDS_ERR_AUTH_FAILED             196
#define IDS_ERR_AUTH_FAILED_CAPTION     197
#define IDR_3MIN_PROGRESS               197
#define IDS_ERR_CAPTION                 198
#define IDR_LISTWINDOWMENU              198
#define IDS_ERR_CONNECT_FAILED          199
#define IDR_LISTWINDOW_CONTEXTMENU      199
#define IDS_ERR_CONNECT_FAILED_CAPTION  200
#define IDS_MENU_TRACKLIST              201
#define IDS_MENU_NICO_RECENT            202
#define IDS_NICO_CONNECTED              203
#define IDS_NICO_PROGRAM_LIST_CAPTION   204
#define IDC_CHK_TOPMOST                 1006
#define IDC_GRP_DISPLAY                 1007
#define IDC_CHK_AMPM                    1008
#define IDC_CHK_TRANSPARENCY            1009
#define IDC_EDIT_TRANSPARENCY           1011
#define IDC_SPIN_TRANSPARENCY           1012
#define IDC_SPEAK_EVERYMIN              1016
#define IDC_SPEAK_EVERYHOUR             1017
#define IDC_RADIO3                      1018
#define IDC_NOSPEAK                     1018
#define IDC_EDIT_NOCO_EMAIL             1031
#define IDC_NICO_PASSWORD               1032
#define IDC_REMEMBERME                  1034
#define IDC_SOUNDFILE                   1035
#define IDC_BTN_SELECT_SNDFILE          1036
#define IDC_CHK_NICOIDPASS_SAVE         1041
#define IDC_EDIT_SEARCHSTRING           1044
#define IDC_BTN_SEARCH                  1045
#define ID_BTN_WHATTIMEISITNOW          40009
#define ID_BTN_ABOUT                    40010
#define ID_BTN_SETTING                  40011
#define ID_BTN_QUIT                     40012
#define ID_BTN_NOCOLOGIN                40075
#define ID_BTN_3MIN                     40077
#define ID_BTN_BROADCASTING_LIST        40080
#define ID_MENU_BTN_SEARCH              40084
#define ID_BTN_GO_BORADCASTING          40087
#define ID_BTN_GO_COMMUNITY             40088

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         40089
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
